### ISSUE TITLE
无法加载

### ISSUE THREAD

**Issue by laiyoi** [mrqx0195/nonebot_plugin_chikari_yinpa#1]
```
02-15 21:21:02 [ERROR] nonebot | Failed to import "nonebot_plugin_chikari_yinpa"
Traceback (most recent call last):
  File "e:\nb\test\bot.py", line 16, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "e:\anaconda\envs\nb\lib\site-packages\nonebot\plugin\load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "e:\anaconda\envs\nb\lib\site-packages\nonebot\plugin\load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "e:\anaconda\envs\nb\lib\site-packages\nonebot\plugin\manager.py", line 176, in load_all_plugins
    return set(
  File "e:\anaconda\envs\nb\lib\site-packages\nonebot\plugin\manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "e:\anaconda\envs\nb\lib\site-packages\nonebot\plugin\manager.py", line 146, in load_plugin
    module = importlib.import_module(
  File "e:\anaconda\envs\nb\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "e:\anaconda\envs\nb\lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "e:\nb\test\plugins\nonebot_plugin_chikari_yinpa\__init__.py", line 9, in <module>
    from .handles import yinpa_Handles
  File "e:\nb\test\plugins\nonebot_plugin_chikari_yinpa\handles.py", line 8, in <module>
    from .data_handles import data,configdata,DHandles
  File "e:\nb\test\plugins\nonebot_plugin_chikari_yinpa\data_handles.py", line 35, in <module>
    configdata = json.load(configfile,strict=False)
  File "e:\anaconda\envs\nb\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "e:\anaconda\envs\nb\lib\json\__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "e:\anaconda\envs\nb\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "e:\anaconda\envs\nb\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by mrqx0195** [comment]
已修复于v1.1.6

**Comment by laiyoi** [comment]
btw现在nb2 2.2.2出了requirement里的nonebot2<2.2.0是不是该改了，我刚安装的时候给我退到2.1.3了

**Comment by mrqx0195** [comment]
因为之前使用的是Pydantic v1，在2.2.0上会有问题
现在已经迁移了（至少加载没啥问题，如果有其他问题就另开个issue罢
