### ISSUE TITLE
Bug: 无法获取帮助菜单

### ISSUE THREAD

**Issue by 360add** [mrqx0195/nonebot_plugin_chikari_yinpa#10]
### 操作系统

Windows

### Python 版本

3.11

### NoneBot 版本

2

### 适配器

2

### 协议端

1

### 描述问题

输入因怕帮助会报错，向up求助
04-27 19:22:01 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_chikari_yinpa, lineno=48) failed.
Traceback (most recent call last):
  File "D:\yld\BOT2\nb2-fast-deploy-main\bot.py", line 67, in <module>
    nonebot.run()
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\nonebot\__init__.py", line 334, in run
    get_driver().run(*args, **kwargs)
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\MAG\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\MAG\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\MAG\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Users\MAG\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\MAG\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\MAG\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\MAG\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 842, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 817, in simple_run
    await handler(
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 106, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\nonebot_plugin_chikari_yinpa\handles.py", line 145, in yinpa_help
    await matcher.finish(MessageSegment.image(Utils.text_to_image(dicts.yinpa_help_dict[""])))
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\nonebot_plugin_chikari_yinpa\utils.py", line 125, in text_to_image
    font = ImageFont.truetype(plugin_config.chikari_yinpa_font, fontSize)
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\PIL\ImageFont.py", line 807, in truetype
    return freetype(font)
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\PIL\ImageFont.py", line 804, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "D:\yld\BOT2\nb2-fast-deploy-main\.venv\Lib\site-packages\PIL\ImageFont.py", line 244, in __init__
    self.font = core.getfont(
OSError: cannot open resource

### 复现步骤

输入因怕帮助会报错

**Comment by 360add** [comment]
**已解决，在插件目录下放入字体就可以了******
