### ISSUE TITLE
Bug: 出现异常

### ISSUE THREAD

**Issue by yokoyamamio** [mrqx0195/nonebot_plugin_chikari_yinpa#14]
### 操作系统

Linux

### Python 版本

3.10.0

### NoneBot 版本

2.3.0

### 适配器

ob11

### 协议端

nt

### 描述问题

```
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/root/QBOT/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/root/QBOT/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/root/QBOT/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/root/QBOT/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/QBOT/.venv/lib/python3.10/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/root/QBOT/.venv/lib/python3.10/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/QBOT/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/QBOT/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/root/QBOT/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/QBOT/.venv/lib/python3.10/site-packages/nonebot_plugin_chikari_yinpa/handles.py", line 75, in yinpa_join
    name: str = await bot.call_api("get_group_member_info",group_id = event.group_id,user_id = uid)["nickname"]
TypeError: 'coroutine' object is not subscriptable
```

### 复现步骤

输入了yinpa_join就这样了

**Comment by mrqx0195** [comment]
已修
