### ISSUE TITLE
启用插件失败

### ISSUE THREAD

**Issue by QSlotus** [mrqx0195/nonebot_plugin_chikari_yinpa#2]
启用插件失败
```
02-16 17:26:50 [ERROR] nonebot | Failed to import "nonebot_plugin_chikari_yinpa"
Traceback (most recent call last):
  File "/data/nb/bot.py", line 23, in <module>
    nonebot.load_plugin("nonebot_plugin_chikari_yinpa")
  File "/usr/local/lib/python3.10/dist-packages/nonebot/plugin/load.py", line 39, in load_plugin
    return manager.load_plugin(module_path)
> File "/usr/local/lib/python3.10/dist-packages/nonebot/plugin/manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/usr/local/lib/python3.10/dist-packages/nonebot/plugin/manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_chikari_yinpa/__init__.py", line 9, in <module>
    from .handles import yinpa_Handles
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_chikari_yinpa/handles.py", line 8, in <module>
    from .data_handles import data,configdata,DHandles
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_chikari_yinpa/data_handles.py", line 14, in <module>
    with open(plugin_data_file,encoding='utf-8')as datafile:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/nonebot2/chikari_yinpa/data.json'
```

**Comment by mrqx0195** [comment]
按理来说前置localstore插件会自动创建文件的（思索）
试着在1.2.1修了一下，没啥问题的话我就close了

**Comment by QSlotus** [comment]
emmmm
用pip install --upgrade 更新之后
插件能启用了，但是在输入指令`/yinpa_help`时报错
```
02-17 10:01:07 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_chikari_yinpa, lineno=48)
02-17 10:01:07 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_chikari_yinpa, lineno=48) running complete
02-17 10:01:07 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_chikari_yinpa, lineno=48) failed.
Traceback (most recent call last):
  File "/data/nb/bot.py", line 44, in <module>
    nonebot.run(app="__mp_main__:app")
  File "/usr/local/lib/python3.10/dist-packages/nonebot/__init__.py", line 333, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/drivers/fastapi.py", line 185, in run
    uvicorn.run(
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/usr/local/lib/python3.10/dist-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/matcher/matcher.py", line 842, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/matcher/matcher.py", line 817, in simple_run
    await handler(
  File "/usr/local/lib/python3.10/dist-packages/nonebot/dependencies/__init__.py", line 106, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_chikari_yinpa/handles.py", line 136, in yinpa_help
    await matcher.finish(MessageSegment.image(Utils.text_to_image(dicts.yinpa_help_dict[""])))
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_chikari_yinpa/utils.py", line 122, in text_to_image
    font = ImageFont.truetype(fontPath, fontSize)
  File "/usr/local/lib/python3.10/dist-packages/PIL/ImageFont.py", line 819, in truetype
    return freetype(font)
  File "/usr/local/lib/python3.10/dist-packages/PIL/ImageFont.py", line 816, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/local/lib/python3.10/dist-packages/PIL/ImageFont.py", line 245, in __init__
    self.font = core.getfont(
OSError: cannot open resource
02-17 10:01:08 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_overbracket, lineno=34)
02-17 10:01:08 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_overbracket, lineno=34) running complete
```

**Comment by mrqx0195** [comment]
……我字体用的是windows下的路径，没考虑过linux……
你试试把字体路径改成已有的字体，我这看看能不能把字体包进包里

**Comment by QSlotus** [comment]
在哪改（

**Comment by mrqx0195** [comment]
修复于v1.2.3

**Comment by QSlotus** [comment]
对了，怎么开启银趴啊（
用了`/yinpa_control` 、`yinpa_control`、`银趴控制`、`/银趴控制` 都没反应 后台也没有报错

**Comment by mrqx0195** [comment]
"/yinpa_control enable"
