### ISSUE TITLE
插件加载失败

### ISSUE THREAD

**Issue by RainbowDashKira** [mrqx0195/nonebot_plugin_chikari_yinpa#3]
[ERROR] nonebot | Failed to import "nonebot_plugin_chikari_yinpa"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\plugin\load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\plugin\load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\plugin\manager.py", line 176, in load_all_plugins
    return set(
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\plugin\manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\plugin\manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot_plugin_chikari_yinpa\__init__.py", line 9, in <module>
    from .handles import yinpa_Handles
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot_plugin_chikari_yinpa\handles.py", line 4, in <module>
    from nonebot import get_driver,get_plugin_config
ImportError: cannot import name 'get_plugin_config' from 'nonebot' (E:\BOT\rainbow\.venv\lib\site-packages\nonebot\__init__.py)

**Comment by RainbowDashKira** [comment]
更新2.2nonebot就好了。
