### ISSUE TITLE
帮助指令好像有bug，后台有报错，信息没有返回

### ISSUE THREAD

**Issue by RainbowDashKira** [mrqx0195/nonebot_plugin_chikari_yinpa#4]
02-19 09:16:42 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_chikari_yinpa, lineno=48) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\__init__.py", line 333, in run
    get_driver().run(*args, **kwargs)
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 185, in run
    uvicorn.run(
  File "E:\BOT\rainbow\.venv\lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "E:\BOT\rainbow\.venv\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once
    handle._run()
  File "C:\Users\10905\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 842, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 817, in simple_run
    await handler(
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 106, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot_plugin_chikari_yinpa\handles.py", line 195, in yinpa_help
    await matcher.finish(MessageSegment.image(Utils.text_to_image("错误：不存在对应的帮助\n可用帮助：\n" + "\n".join(list(dicts.yinpa_help_dict.keys())))))
  File "E:\BOT\rainbow\.venv\lib\site-packages\nonebot_plugin_chikari_yinpa\utils.py", line 125, in text_to_image
    font = ImageFont.truetype(plugin_config.chikari_yinpa_font, fontSize)
  File "E:\BOT\rainbow\.venv\lib\site-packages\PIL\ImageFont.py", line 996, in truetype
    return freetype(font)
  File "E:\BOT\rainbow\.venv\lib\site-packages\PIL\ImageFont.py", line 993, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "E:\BOT\rainbow\.venv\lib\site-packages\PIL\ImageFont.py", line 239, in __init__
    font_bytes_path = font if isinstance(font, bytes) else font.encode()
AttributeError: 'WindowsPath' object has no attribute 'encode'

**Comment by mrqx0195** [comment]
尝试更新pillow至最新版
`pip install --upgrade pillow`

**Comment by mrqx0195** [comment]
如果没有再出现问题的话我就close了

**Comment by RainbowDashKira** [comment]
是pillow的问题，解决了。
