### ISSUE TITLE
Bug: 不知道是配置问题还是什么，错误提示OSError: cannot open resource

### ISSUE THREAD

**Issue by VAHua** [mrqx0195/nonebot_plugin_chikari_yinpa#5]
### 操作系统

Windows

### Python 版本

3.10

### NoneBot 版本

2.0

### 适配器

Onebot V11

### 协议端

go-cqhttp 1.2

### 描述问题

查询种族信息yinpa_help species 魅魔，后台报错
[ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_chikari_yinpa, lineno=48
) failed.
Traceback (most recent call last):
  File "E:\qqbot\robot\bot.py", line 32, in <module>
    nonebot.run(app="__mp_main__:app")
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot\__init__.py", line 333, in run
    get_driver().run(*args, **kwargs)
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot\drivers\fastapi.py", line 185, in run
    uvicorn.run(
  File "D:\Program Files (x86)\python\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "D:\Program Files (x86)\python\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\Program Files (x86)\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Program Files (x86)\python\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "D:\Program Files (x86)\python\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Program Files (x86)\python\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "D:\Program Files (x86)\python\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "D:\Program Files (x86)\python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "D:\Program Files (x86)\python\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot\internal\matcher\matcher.py", line 842, in run 
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot\internal\matcher\matcher.py", line 817, in simp
le_run
    await handler(
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot\dependencies\__init__.py", line 106, in __call_
_
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot_plugin_chikari_yinpa\handles.py", line 152, in 
yinpa_help
    await matcher.finish(MessageSegment.image(Utils.text_to_image(dicts.species_help[help_key[1]])))
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot_plugin_chikari_yinpa\utils.py", line 125, in te
xt_to_image
    font = ImageFont.truetype(plugin_config.chikari_yinpa_font, fontSize)
  File "D:\Program Files (x86)\python\lib\site-packages\PIL\ImageFont.py", line 819, in truetype
    return freetype(font)
  File "D:\Program Files (x86)\python\lib\site-packages\PIL\ImageFont.py", line 816, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "D:\Program Files (x86)\python\lib\site-packages\PIL\ImageFont.py", line 245, in __init__
    self.font = core.getfont(
OSError: cannot open resource

### 复现步骤

查询种族信息yinpa_help species 魅魔

### 期望的结果

正常发送指令响应，求大佬帮助

**Comment by VAHua** [comment]
解决了，我去config改了字体路径，但是现在报出了另一个问题，使用指令info报错
[ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_chikari_yinpa, lineno=40
) failed.
Traceback (most recent call last):
  File "E:\qqbot\robot\bot.py", line 32, in <module>
    nonebot.run(app="__mp_main__:app")
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot\__init__.py", line 333, in run
    get_driver().run(*args, **kwargs)
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot\drivers\fastapi.py", line 185, in run
    uvicorn.run(
  File "D:\Program Files (x86)\python\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "D:\Program Files (x86)\python\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\Program Files (x86)\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Program Files (x86)\python\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "D:\Program Files (x86)\python\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Program Files (x86)\python\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "D:\Program Files (x86)\python\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "D:\Program Files (x86)\python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "D:\Program Files (x86)\python\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot\internal\matcher\matcher.py", line 842, in run 
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot\internal\matcher\matcher.py", line 817, in simp
le_run
    await handler(
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot\dependencies\__init__.py", line 106, in __call_
_
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot_plugin_chikari_yinpa\handles.py", line 211, in 
yinpa_info
    at:list = Utils.get_at(event)
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot_plugin_chikari_yinpa\utils.py", line 81, in get
_at
    msg = json.loads(event.model_dump_json())
AttributeError: 'GroupMessageEvent' object has no attribute 'model_dump_json'

**Comment by mrqx0195** [comment]
于1.2.8修复
