### ISSUE TITLE
Bug: IndexError: list index out of range

### ISSUE THREAD

**Issue by ghost** [mrqx0195/nonebot_plugin_chikari_yinpa#8]
### 操作系统

Windows

### Python 版本

3.12.2

### NoneBot 版本

2.2.1

### 适配器

Onebot V11

### 协议端

LiteLoaderQQNT Onebot 3.16.1

### 描述问题

标题所说，使用部分指令时会出这个问题

### 复现步骤

输入/kou，/chong这些指令时会报这个错误

### 截图或日志

```
03-25 00:37:08 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_chikari_yinpa, lineno=88) failed.
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\nonebot\__init__.py", line 334, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\nonebot\drivers\none.py", line 56, in run
    loop.run_until_complete(self._serve())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 672, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 639, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1985, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 842, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 817, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\nonebot\dependencies\__init__.py", line 106, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\nonebot_plugin_chikari_yinpa\handles.py", line 505, in yinpa_chong
    oc = Utils.operation_check(uid)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\nonebot_plugin_chikari_yinpa\utils.py", line 461, in operation_check
    Utils.refresh_data(uid)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\nonebot_plugin_chikari_yinpa\utils.py", line 188, in refresh_data
    DHandles.skill_refresh(uid,i[0],i[1])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\nonebot_plugin_chikari_yinpa\data_handles.py", line 146, in skill_refresh
    if data[uid]["skill"][i][2] <= 0:
IndexError: list index out of range
```

**Comment by mrqx0195** [comment]
已修复于v1.3.5
